
# DATABASE CONNECTION
spring.datasource.url=jdbc:sqlserver://CROCODIN-PC:1433;databaseName=TankingTanksMini;encrypt=true;trustServerCertificate=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# HIKARI CONNECTION POOL
# Minimum connections kept open even when idle
spring.datasource.hikari.minimum-idle=2
# Max connections in the pool at once
spring.datasource.hikari.maximum-pool-size=10
# How long to wait for a free connection (ms)
spring.datasource.hikari.connection-timeout=30000
# How long an idle connection stays in pool before being dropped
spring.datasource.hikari.idle-timeout=600000
# Maximum lifetime of any connection in the pool
spring.datasource.hikari.max-lifetime=1800000

# JPA / HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# LOGGING / Slf4j
logging.level.root=INFO
logging.level.ubb.dbsm=DEBUG
logging.file.name=logs/app.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n

# EhCache
spring.cache.type=jcache
spring.cache.jcache.config=classpath:ehcache.xml
spring.cache.jcache.provider=org.ehcache.jsr107.EhcacheCachingProvider

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/master.xml